import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale, type Locale } from "@/i18n/config";

export default function ClubsPage({ params }: { params:{locale:string} }) {
  if (!isLocale(params.locale)) notFound(); const locale:Locale=params.locale; const bn=locale==="bn";
  const clubs=bn?["ICT · Robotics · Coding","Music","Scout","Language","Sports","Cultural Activities"]:["ICT · Robotics · Coding","Music","Scout","Language","Sports","Cultural Activities"];
  return <main className="kc-subpage"><section className="kc-clubs-hero kc-section-wide"><div><span className="kc-overline">01 · {bn ? "ক্লাব ও কার্যক্রম" : "Clubs & activities"}</span><h1>{bn ? "আগ্রহের জায়গা খুঁজে নেওয়ার সুযোগ।" : "Room to follow an interest beyond the syllabus."}</h1><p>{bn ? "ICT, Robotics & Coding, Music, Scout, Language, Sports এবং সাংস্কৃতিক কার্যক্রমসহ বিভিন্ন ক্লাব ও সহশিক্ষা কার্যক্রম রয়েছে।" : "KCMSC offers clubs and co-curricular activities including ICT, Robotics & Coding, Music, Scout, Language, Sports and cultural activities."}</p></div><div className="kc-clubs-image"><Image src="/kcmsc/media/vibrant_student_culture.jpg" alt="KCMSC student activity" fill priority sizes="(min-width:900px) 50vw, 100vw" className="object-cover" /></div></section><section className="kc-clubs-list"><div className="kc-section-wide"><div className="kc-section-heading"><div><span className="kc-overline">02 · {bn ? "ছয়টি জায়গা" : "Six directions"}</span><h2>{bn ? "স্কুলের বাইরে শেখারও নিজস্ব পথ আছে।" : "Learning outside class has its own routes."}</h2></div></div><div className="kc-club-list-large">{clubs.map((club,i)=><div key={club}><span>0{i+1}</span><h3>{club}</h3><b>↗</b></div>)}</div></div></section><section className="kc-clubs-feature kc-section-wide"><div><Image src="/kcmsc/media/ict_olympiad_at_kc.jpg" alt="KCMSC ICT activity" fill sizes="(min-width:900px) 55vw, 100vw" className="object-cover" /></div><section><span className="kc-overline">03 · {bn ? "অংশগ্রহণ" : "Participation"}</span><h2>{bn ? "আগ্রহকে কাজের জায়গা দেওয়া।" : "Giving interests somewhere to become practice."}</h2><p>{bn ? "ক্লাব, প্রতিযোগিতা ও সহশিক্ষা কার্যক্রম শিক্ষার্থীদের নিয়মিত পাঠের বাইরে অংশ নেওয়ার সুযোগ তৈরি করে।" : "Clubs, competitions and co-curricular activities give students space to participate beyond regular lessons."}</p><Link href={`/${locale}/student-life`} className="kc-text-link">{bn ? "শিক্ষার্থী জীবন" : "Student life"}<span>↗</span></Link></section></section></main>;
}
