import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale, type Locale } from "@/i18n/config";

export default function FacilitiesPage({ params }: { params: { locale: string } }) {
  if (!isLocale(params.locale)) notFound(); const locale: Locale = params.locale; const bn = locale === "bn";
  const items = bn ? [["01","কম্পিউটার ল্যাব","৫০+ কম্পিউটারসহ এয়ার-কন্ডিশন্ড কম্পিউটার ল্যাব।","/kcmsc/media/kcmsc3.jpg"],["02","লাইব্রেরি","১০,০০০+ বই ও ডিজিটাল রিসোর্সসহ লাইব্রেরি।","/kcmsc/media/students_at_library.jpg"],["03","বিজ্ঞান ল্যাব","বিজ্ঞান শেখার জন্য ব্যবহারিক ল্যাব সুবিধা।","/kcmsc/media/teacher_taking_class.jpg"],["04","ছাদবাগান","চারটি দশতলা ভবনের ছাদে বাগান।","/kcmsc/media/rooftop_garden.jpg"]] : [["01","Computer lab","An air-conditioned computer lab with 50+ PCs.","/kcmsc/media/kcmsc3.jpg"],["02","Library","A library with 10,000+ books and digital resources.","/kcmsc/media/students_at_library.jpg"],["03","Science labs","Practical laboratory space supporting science learning.","/kcmsc/media/teacher_taking_class.jpg"],["04","Rooftop gardens","Gardens across the roofs of four ten-storied buildings.","/kcmsc/media/rooftop_garden.jpg"]];
  return <main className="kc-subpage"><section className="kc-facility-hero kc-section-wide"><div><span className="kc-overline">01 · {bn ? "ক্যাম্পাস" : "Campus"}</span><h1>{bn ? "যে জায়গাগুলো প্রতিদিনের শেখাকে সহায়তা করে।" : "Spaces that support the everyday work of learning."}</h1><p>{bn ? "KCMSC-এর ক্যাম্পাসে শ্রেণিকক্ষের পাশাপাশি লাইব্রেরি, ল্যাব, কম্পিউটার সুবিধা, খেলাধুলার স্থান ও ছাদবাগান রয়েছে।" : "Alongside classrooms, KCMSC provides library, laboratory, computer, sports and rooftop-garden spaces that support school life."}</p></div><div className="kc-facility-hero-image"><Image src="/kcmsc/media/kcmsc3.jpg" alt="KCMSC campus" fill priority sizes="(min-width:900px) 50vw, 100vw" className="object-cover" /></div></section><section className="kc-facility-list"><div className="kc-section-wide"><div className="kc-section-heading"><div><span className="kc-overline">02 · {bn ? "সুবিধাসমূহ" : "Facilities"}</span><h2>{bn ? "ক্যাম্পাসকে একটি তালিকা নয়, ব্যবহারযোগ্য জায়গা হিসেবে দেখুন।" : "Think of the campus as working spaces, not just a list of facilities."}</h2></div></div><div className="kc-facility-grid">{items.map(([n,title,text,image])=><article key={n}><div><Image src={image} alt={title} fill sizes="(min-width:900px) 50vw, 100vw" className="object-cover" /></div><section><span>{n}</span><h3>{title}</h3><p>{text}</p></section></article>)}</div></div></section><section className="kc-facility-sports"><div className="kc-section-wide"><div><span className="kc-overline">03 · {bn ? "স্কুলজীবন" : "School life"}</span><h2>{bn ? "খেলাধুলা ও কার্যক্রমের জন্যও জায়গা আছে।" : "There is space for sport and activities too."}</h2><p>{bn ? "স্পোর্টস ক্লাব, ICT, Robotics & Coding, Music, Scout, Language এবং অন্যান্য সহশিক্ষা কার্যক্রম ক্যাম্পাসজীবনের অংশ।" : "Sports, ICT, Robotics & Coding, Music, Scout, Language and other co-curricular activities are part of campus life."}</p><Link href={`/${locale}/student-life`} className="kc-text-link">{bn ? "শিক্ষার্থী জীবন" : "Student life"}<span>↗</span></Link></div><div className="kc-sports-image"><Image src="/kcmsc/media/students_having_fun_after_sports.jpg" alt="KCMSC students after sports" fill sizes="(min-width:900px) 50vw, 100vw" className="object-cover" /></div></div></section></main>;
}
