import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getDictionary, isLocale, type Locale } from "@/i18n/config";
import { prisma } from "@/lib/db";

type Entry = { year: string; category: string; title: string; details: string };
async function getEntries(locale: Locale, fallback: Entry[]) {
  try { const rows = await prisma.achievement.findMany({ orderBy: [{ year: "desc" }, { createdAt: "desc" }] }); if (!rows.length) return fallback; return rows.map(r => ({ year:String(r.year), category:r.category, title:locale === "bn" ? r.titleBn : r.titleEn, details:locale === "bn" ? r.descriptionBn : r.descriptionEn })); } catch { return fallback; }
}
export default async function AchievementsPage({ params }: { params:{locale:string} }) {
  if (!isLocale(params.locale)) notFound(); const locale:Locale=params.locale; const bn=locale==="bn"; const dict=getDictionary(locale); const entries=await getEntries(locale, dict.achievementsPage.entries);
  return <main className="kc-subpage"><section className="kc-achievement-hero kc-section-wide"><div><span className="kc-overline">01 · {bn ? "ফলাফল ও অর্জন" : "Results & achievements"}</span><h1>{bn ? "ফলাফল শুধু সংখ্যা নয়।" : "Results are more than numbers."}</h1><p>{bn ? "বোর্ড পরীক্ষা, প্রতিযোগিতা, বৃত্তি ও বিভিন্ন অর্জন শিক্ষার্থীদের স্কুলজীবনের বিভিন্ন দিককে তুলে ধরে।" : "Board examinations, competitions, scholarships and recognition show different parts of student life at KCMSC."}</p><div className="kc-achievement-links"><Link href={`/${locale}/academics`} className="kc-solid-button">{bn ? "একাডেমিক" : "Academics"}<span>↗</span></Link><Link href={`/${locale}/student-life`} className="kc-outline-button">{bn ? "শিক্ষার্থী জীবন" : "Student life"}</Link></div></div><div className="kc-achievement-image"><Image src="/kcmsc/media/ict_olympiad_at_kc.jpg" alt="KCMSC students at an ICT activity" fill priority sizes="(min-width:900px) 50vw, 100vw" className="object-cover" /></div></section><section className="kc-achievement-record"><div className="kc-section-wide"><div className="kc-section-heading"><div><span className="kc-overline">02 · {bn ? "বোর্ড ফলাফল" : "Board results"}</span><h2>{bn ? "২০২৪ সালের ফলাফল।" : "The 2024 board results."}</h2></div></div><div className="kc-achievement-results"><div><span>SSC 2024</span><strong>98.48%</strong><p>130 {bn ? "পরীক্ষার্থী" : "candidates"} · 128 {bn ? "উত্তীর্ণ" : "passed"} · 67 GPA 5</p></div><div><span>HSC 2024</span><strong>100%</strong><p>47 {bn ? "পরীক্ষার্থী" : "candidates"} · 47 {bn ? "উত্তীর্ণ" : "passed"} · 13 GPA 5</p></div></div></div></section><section className="kc-achievement-list"><div className="kc-section-wide"><div className="kc-section-heading"><div><span className="kc-overline">03 · {bn ? "রেকর্ড" : "The record"}</span><h2>{bn ? "অন্যান্য অর্জন ও স্বীকৃতি।" : "Other achievements and recognition."}</h2></div></div><div className="kc-achievement-entries">{entries.map((entry,i)=><article key={`${entry.year}-${entry.title}-${i}`}><span>{entry.year}</span><div><small>{entry.category}</small><h3>{entry.title}</h3><p>{entry.details}</p></div><b>0{i+1}</b></article>)}</div></div></section></main>;
}
