import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale, type Locale } from "@/i18n/config";

export default function AcademicsPage({ params }: { params: { locale: string } }) {
  if (!isLocale(params.locale)) notFound(); const locale: Locale = params.locale; const bn = locale === "bn";
  const wing = bn ? [["Junior Wing","Pre-Primary · Primary","৭৬ জন শিক্ষক","Pre-Primary ও Primary শিক্ষা"],["Senior Wing","Secondary · Higher Secondary","২২ Lecturer · ২০ Senior Teacher · ২২ Assistant Teacher","Secondary ও Higher Secondary শিক্ষা"]] : [["Junior Wing","Pre-Primary · Primary","76 teachers","Pre-Primary and Primary education"],["Senior Wing","Secondary · Higher Secondary","22 Lecturers · 20 Senior Teachers · 22 Assistant Teachers","Secondary and Higher Secondary education"]];
  const curriculum = bn ? ["জাতীয় শিক্ষাক্রম", "বাংলা ভার্সন · ১,২৪০ শিক্ষার্থী", "ইংরেজি ভার্সন · ১,০৯৬ শিক্ষার্থী", "Play Group → Grade XII"] : ["National Curriculum", "Bangla Version · 1,240 students", "English Version · 1,096 students", "Play Group → Grade XII"];
  return <main className="kc-subpage">
    <section className="kc-academic-hero kc-section-wide"><div><span className="kc-overline">01 · {bn ? "একাডেমিক" : "Academics"}</span><h1>{bn ? "স্কুলজীবনের একটি স্পষ্ট শিক্ষাপথ।" : "A clear path through school."}</h1><p>{bn ? "প্রাথমিক শিক্ষা থেকে মাধ্যমিক ও উচ্চমাধ্যমিক পর্যন্ত KCMSC একটি ধারাবাহিক একাডেমিক কাঠামোর মধ্যে শিক্ষার্থীদের এগিয়ে নেয়।" : "KCMSC brings early learning, primary, secondary and higher secondary education into one continuous academic structure."}</p><div className="kc-academic-note"><strong>Play Group → Grade XII</strong><span>{bn ? "বাংলা ও ইংরেজি ভার্সন" : "Bangla & English Versions"}</span></div></div><div className="kc-academic-image"><Image src="/kcmsc/media/teacher_taking_class.jpg" alt="KCMSC classroom" fill priority sizes="(min-width:900px) 50vw, 100vw" className="object-cover" /></div></section>
    <section className="kc-academic-glance"><div className="kc-section-wide"><div className="kc-section-label"><span>{bn ? "০২ · এক নজরে" : "02 · At a glance"}</span><i /></div><div className="kc-academic-stats"><div><strong>2,336</strong><span>{bn ? "শিক্ষার্থী" : "Students"}</span></div><div><strong>53%</strong><span>{bn ? "বাংলা ভার্সন" : "Bangla Version"}</span></div><div><strong>47%</strong><span>{bn ? "ইংরেজি ভার্সন" : "English Version"}</span></div><div><strong>7:45–2:30</strong><span>{bn ? "রবি–বৃহস্পতি" : "Sun–Thu"}</span></div></div></div></section>
    <section className="kc-academic-wings"><div className="kc-section-wide"><div className="kc-section-heading"><div><span className="kc-overline">03 · {bn ? "কাঠামো" : "Structure"}</span><h2>{bn ? "একটি স্কুল, শিক্ষার বিভিন্ন ধাপ।" : "One school, different stages of learning."}</h2></div></div><div className="kc-wing-grid">{wing.map(([name,eyebrow,staff,body],i)=><article key={name}><span>0{i+1}</span><p>{eyebrow}</p><h3>{name}</h3><div>{body}</div><b>{staff}</b></article>)}</div></div></section>
    <section className="kc-academic-classroom kc-section-wide"><div className="kc-academic-classroom-image"><Image src="/kcmsc/media/students_at_library.jpg" alt="KCMSC students" fill sizes="(min-width:900px) 48vw, 100vw" className="object-cover" /></div><div><span className="kc-overline">04 · {bn ? "শিক্ষার পরিবেশ" : "Learning environment"}</span><h2>{bn ? "শেখা শুধু পরীক্ষার জন্য নয়।" : "Learning is not only about examinations."}</h2><p>{bn ? "নিয়মিত শ্রেণিকক্ষের পাঠদান, শিক্ষক, লাইব্রেরি, কম্পিউটার ও বিজ্ঞান ল্যাব একসঙ্গে শিক্ষার্থীদের দৈনন্দিন শিক্ষাকে সহায়তা করে।" : "Regular classroom teaching, teachers, library resources, computer and science laboratories support the everyday academic experience."}</p><Link href={`/${locale}/facilities`} className="kc-text-link">{bn ? "সুবিধাসমূহ" : "Campus facilities"}<span>↗</span></Link></div></section>
    <section className="kc-academic-results"><div className="kc-section-wide"><div><span className="kc-overline">05 · {bn ? "ফলাফল" : "Results"}</span><h2>{bn ? "২০২৪ সালের বোর্ড ফলাফল।" : "The 2024 board results."}</h2></div><div className="kc-academic-result-grid"><div><span>SSC 2024</span><strong>98.48%</strong><p>130 {bn ? "পরীক্ষার্থী" : "candidates"} · 128 {bn ? "উত্তীর্ণ" : "passed"} · 67 GPA 5</p></div><div><span>HSC 2024</span><strong>100%</strong><p>47 {bn ? "পরীক্ষার্থী" : "candidates"} · 47 {bn ? "উত্তীর্ণ" : "passed"} · 13 GPA 5</p></div></div></div></section>
    <section className="kc-academic-curriculum"><div className="kc-section-wide"><div><span className="kc-overline">06 · {bn ? "শিক্ষাক্রম" : "Curriculum"}</span><h2>{bn ? "জাতীয় শিক্ষাক্রম, দুটি ভাষার ভার্সন।" : "National curriculum, two language versions."}</h2></div><div className="kc-curriculum-list">{curriculum.map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong></div>)}</div></div></section>
  </main>;
}
